### ISSUE TITLE
Extrair PROMs TBP28L22 usando um Arduino

### ISSUE THREAD

**Issue by felipesanches** [ArqueologiaDigital/EmuHC#5]
Para ler as PROMs (u98, u99, u82 e u19) que supostamente são configuração de memory-map do Nexus2600 (#2) pensamos em usar o leitor MiniPro. Mas ele não suporta esse modelo de memória. Então precisaremos fazer nosso próprio leitor. Dá pra fazer usando um Arduino e seguindo o datasheet, disponível aqui:
http://pdf1.alldatasheet.com/datasheet-pdf/view/28766/TI/TBP28L22MJ.html

**Comment by felipesanches** [comment]
![screenshot at 2018-01-29 15 21 58](https://user-images.githubusercontent.com/213676/35586625-7541c160-05e2-11e8-9902-097e393013f5.png)

**Comment by affonsoamendola** [comment]
Montei o arduino seguindo as conexões da datasheet e obtive as roms com sucesso (Eu acho, tem que dar uma olhada nelas com cuidado)
